# The URL the site will be built for
base_url = "https://example.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "sam"

taxonomies = [
    { name = "tags", rss = true },
    { name = "authors", rss = true }
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

show_word_count = true
show_reading_time = true

date_format = "%a %b %e, %Y"

home = "home"

sam_menu = [
    { text = "posts", link = "/posts" },
    { text = "about", link = "/about" },
    { text = "github", link = "https://github.com" }
]

sam_bottom_menu = true

[extra.sam_footer]
text = "Some footer text."
